# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a2a71c245119f1f5f9df50296c6f6a9260e0ee2fdcec803867df32f5c3484dfbe9f599773e4f2fe95b5f19d855976df50f529f3c2a01c70832bddb79fe31667

test:
  secret_key_base: 1706768e40095e4d849d4a061aa2cbf31763ce621f2a214f1a8f1f25b7f2b8909933f2469a8f542ffdb98a5b94d067318e1b5023399cc38b04b5d44c669ee2cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
